class Autogenerated {
  IssPosition? issPosition;
  String? message;
  int? timestamp;

  Autogenerated({this.issPosition, this.message, this.timestamp});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    issPosition = json['iss_position'] != null
        ? IssPosition.fromJson(json['iss_position'])
        : null;
    message = json['message'];
    timestamp = json['timestamp'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (issPosition != null) {
      data['iss_position'] = issPosition!.toJson();
    }
    data['message'] = message;
    data['timestamp'] = timestamp;
    return data;
  }
}

class IssPosition {
  String? latitude;
  String? longitude;

  IssPosition({this.latitude, this.longitude});

  IssPosition.fromJson(Map<String, dynamic> json) {
    latitude = json['latitude'];
    longitude = json['longitude'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['latitude'] = latitude;
    data['longitude'] = longitude;
    return data;
  }
}
