import 'dart:convert';
import 'dart:developer';

import 'package:ano/modals/newmodel.dart';
import 'package:http/http.dart' as http;

class BackEnd {
  static Future<Autogenerated?> callAPI() async {
    try {
      // var api = "https://www.boredapi.com/api/activity";
      var loc = "http://api.open-notify.org/iss-now.json";

      final response = await http.get(Uri.parse(loc));
      final data = jsonDecode(response.body);
      return Autogenerated.fromJson(data);
    } catch (e) {
      log(e.toString());
    }
    return null;
  }
}
